server:
  port: 8088

spring:
  application:
    name: spring-ai-demo
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  redis:
    host: <YOU_REDIS_HOST>
    port: <YOU_REDIS_PORT>
    password: <YOU_REDIS_PASSWORD>
  datasource:
    url: jdbc:postgresql://<YOU_POSTGRE_HOST>/<YOU_POSTGRE_DATABASE>?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
    username: <YOU_POSTGRE_USER_NAME>
    password: <YOU_POSTGRE_PASSWORD>
    driver-class-name: org.postgresql.Driver
  ai:
    minimax:
      api-key: <YOU_MINIMAX_API_KEY>
      base-url: https://api.minimaxi.com
    kimi:
      api-key: <YOU_KIMI_API_KEY>
      base-url: https://api.moonshot.cn
    zhipu:
      api-key: <YOU_ZHIPU_API_KEY>
      base-url: https://open.bigmodel.cn/api/paas
    qwen:
      api-key: <YOU_QWEN_API_KEY>
      base-url: https://dashscope.aliyuncs.com/compatible-mode
    openai:
      api-key: <YOU_OPENAI_API_KEY>
      base-url: https://api.openai-proxy.org/v1

dify:
  api-key: <YOU_DIFY_API_KEY>
  base-url: <YOU_DIFY_URL>
  dataset-id: <YOU_DIFY_DATASET_ID>
