-- ----------------------------
-- Sequence structure for ai_chat_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."ai_chat_id_seq";
CREATE SEQUENCE "public"."ai_chat_id_seq"
    INCREMENT 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1;
ALTER SEQUENCE "public"."ai_chat_id_seq" OWNER TO "root";

-- ----------------------------
-- Sequence structure for ai_chat_record_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."ai_chat_record_id_seq";
CREATE SEQUENCE "public"."ai_chat_record_id_seq"
    INCREMENT 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1;
ALTER SEQUENCE "public"."ai_chat_record_id_seq" OWNER TO "root";

-- ----------------------------
-- Sequence structure for ai_chat_record_msg_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."ai_chat_record_msg_id_seq";
CREATE SEQUENCE "public"."ai_chat_record_msg_id_seq"
    INCREMENT 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1;
ALTER SEQUENCE "public"."ai_chat_record_msg_id_seq" OWNER TO "root";

-- ----------------------------
-- Sequence structure for ai_role_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."ai_role_id_seq";
CREATE SEQUENCE "public"."ai_role_id_seq"
    INCREMENT 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1;
ALTER SEQUENCE "public"."ai_role_id_seq" OWNER TO "root";

-- ----------------------------
-- Sequence structure for ai_user_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."ai_user_id_seq";
CREATE SEQUENCE "public"."ai_user_id_seq"
    INCREMENT 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1;
ALTER SEQUENCE "public"."ai_user_id_seq" OWNER TO "root";

-- ----------------------------
-- Sequence structure for ai_user_role_rel_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."ai_user_role_rel_id_seq";
CREATE SEQUENCE "public"."ai_user_role_rel_id_seq"
    INCREMENT 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1;
ALTER SEQUENCE "public"."ai_user_role_rel_id_seq" OWNER TO "root";

-- ----------------------------
-- Table structure for ai_chat
-- ----------------------------
DROP TABLE IF EXISTS "public"."ai_chat";
CREATE TABLE "public"."ai_chat"
(
    "id"          int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
        MINVALUE 1
        MAXVALUE 9223372036854775807
        START 1
        CACHE 1
        ),
    "user_id"     int8 NOT NULL,
    "title"       varchar(255) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
    "create_by"   varchar(255) COLLATE "pg_catalog"."default",
    "update_by"   varchar(255) COLLATE "pg_catalog"."default",
    "create_time" timestamp(6)                                DEFAULT now(),
    "update_time" timestamp(6)                                DEFAULT now(),
    "del_flag"    bool                                        DEFAULT false,
    "type"        varchar(30) COLLATE "pg_catalog"."default"  DEFAULT 'CHAT'::character varying
)
;
ALTER TABLE "public"."ai_chat"
    OWNER TO "root";
COMMENT ON COLUMN "public"."ai_chat"."id" IS 'id';
COMMENT ON COLUMN "public"."ai_chat"."user_id" IS '用戶id';
COMMENT ON COLUMN "public"."ai_chat"."title" IS '标题';
COMMENT ON COLUMN "public"."ai_chat"."create_by" IS '创建人';
COMMENT ON COLUMN "public"."ai_chat"."update_by" IS '修改人';
COMMENT ON COLUMN "public"."ai_chat"."create_time" IS '创建时间';
COMMENT ON COLUMN "public"."ai_chat"."update_time" IS '修改时间';
COMMENT ON COLUMN "public"."ai_chat"."del_flag" IS '逻辑删除';
COMMENT ON COLUMN "public"."ai_chat"."type" IS '对话类型';

-- ----------------------------
-- Table structure for ai_chat_record
-- ----------------------------
DROP TABLE IF EXISTS "public"."ai_chat_record";
CREATE TABLE "public"."ai_chat_record"
(
    "id"          int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
        MINVALUE 1
        MAXVALUE 9223372036854775807
        START 1
        CACHE 1
        ),
    "chat_id"     int8 NOT NULL,
    "parent_id"   int8 NOT NULL                               DEFAULT 0,
    "msg_id"      int8 NOT NULL,
    "name"        varchar(100) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
    "create_by"   varchar(255) COLLATE "pg_catalog"."default",
    "update_by"   varchar(255) COLLATE "pg_catalog"."default",
    "create_time" timestamp(6)                                DEFAULT now(),
    "update_time" timestamp(6)                                DEFAULT now(),
    "del_flag"    bool                                        DEFAULT false
)
;
ALTER TABLE "public"."ai_chat_record"
    OWNER TO "root";
COMMENT ON COLUMN "public"."ai_chat_record"."id" IS 'id';
COMMENT ON COLUMN "public"."ai_chat_record"."chat_id" IS '对话ID';
COMMENT ON COLUMN "public"."ai_chat_record"."parent_id" IS '父ID';
COMMENT ON COLUMN "public"."ai_chat_record"."msg_id" IS '消息ID';
COMMENT ON COLUMN "public"."ai_chat_record"."name" IS '对话主体名称';
COMMENT ON COLUMN "public"."ai_chat_record"."create_by" IS '创建人';
COMMENT ON COLUMN "public"."ai_chat_record"."update_by" IS '修改人';
COMMENT ON COLUMN "public"."ai_chat_record"."create_time" IS '创建时间';
COMMENT ON COLUMN "public"."ai_chat_record"."update_time" IS '修改时间';
COMMENT ON COLUMN "public"."ai_chat_record"."del_flag" IS '逻辑删除';

-- ----------------------------
-- Table structure for ai_chat_record_msg
-- ----------------------------
DROP TABLE IF EXISTS "public"."ai_chat_record_msg";
CREATE TABLE "public"."ai_chat_record_msg"
(
    "id"          int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
        MINVALUE 1
        MAXVALUE 9223372036854775807
        START 1
        CACHE 1
        ),
    "msg_detail"  jsonb,
    "create_by"   varchar(255) COLLATE "pg_catalog"."default",
    "update_by"   varchar(255) COLLATE "pg_catalog"."default",
    "create_time" timestamp(6) DEFAULT now(),
    "update_time" timestamp(6) DEFAULT now(),
    "del_flag"    bool         DEFAULT false
)
;
ALTER TABLE "public"."ai_chat_record_msg"
    OWNER TO "root";
COMMENT ON COLUMN "public"."ai_chat_record_msg"."id" IS 'id';
COMMENT ON COLUMN "public"."ai_chat_record_msg"."msg_detail" IS '消息详情内容JSON';
COMMENT ON COLUMN "public"."ai_chat_record_msg"."create_by" IS '创建人';
COMMENT ON COLUMN "public"."ai_chat_record_msg"."update_by" IS '修改人';
COMMENT ON COLUMN "public"."ai_chat_record_msg"."create_time" IS '创建时间';
COMMENT ON COLUMN "public"."ai_chat_record_msg"."update_time" IS '修改时间';
COMMENT ON COLUMN "public"."ai_chat_record_msg"."del_flag" IS '逻辑删除';

-- ----------------------------
-- Table structure for ai_role
-- ----------------------------
DROP TABLE IF EXISTS "public"."ai_role";
CREATE TABLE "public"."ai_role"
(
    "id"          int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
        MINVALUE 1
        MAXVALUE 9223372036854775807
        START 1
        CACHE 1
        ),
    "name"        varchar(100) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
    "code"        varchar(100) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
    "create_by"   varchar(255) COLLATE "pg_catalog"."default",
    "update_by"   varchar(255) COLLATE "pg_catalog"."default",
    "create_time" timestamp(6)                                DEFAULT now(),
    "update_time" timestamp(6)                                DEFAULT now(),
    "del_flag"    bool                                        DEFAULT false
)
;
ALTER TABLE "public"."ai_role"
    OWNER TO "root";
COMMENT ON COLUMN "public"."ai_role"."id" IS 'id';
COMMENT ON COLUMN "public"."ai_role"."name" IS '角色名称';
COMMENT ON COLUMN "public"."ai_role"."code" IS '角色编码';
COMMENT ON COLUMN "public"."ai_role"."create_by" IS '创建人';
COMMENT ON COLUMN "public"."ai_role"."update_by" IS '修改人';
COMMENT ON COLUMN "public"."ai_role"."create_time" IS '创建时间';
COMMENT ON COLUMN "public"."ai_role"."update_time" IS '修改时间';
COMMENT ON COLUMN "public"."ai_role"."del_flag" IS '逻辑删除';

-- ----------------------------
-- Table structure for ai_user
-- ----------------------------
DROP TABLE IF EXISTS "public"."ai_user";
CREATE TABLE "public"."ai_user"
(
    "id"          int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
        MINVALUE 1
        MAXVALUE 9223372036854775807
        START 1
        CACHE 1
        ),
    "account_no"  varchar(100) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
    "name"        varchar(100) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
    "password"    varchar(100) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
    "salt"        varchar(100) COLLATE "pg_catalog"."default" DEFAULT ''::character varying,
    "status"      bool                                        DEFAULT true,
    "create_by"   varchar(255) COLLATE "pg_catalog"."default",
    "update_by"   varchar(255) COLLATE "pg_catalog"."default",
    "create_time" timestamp(6)                                DEFAULT now(),
    "update_time" timestamp(6)                                DEFAULT now(),
    "del_flag"    bool                                        DEFAULT false
)
;
ALTER TABLE "public"."ai_user"
    OWNER TO "root";
COMMENT ON COLUMN "public"."ai_user"."id" IS 'id';
COMMENT ON COLUMN "public"."ai_user"."account_no" IS '账号';
COMMENT ON COLUMN "public"."ai_user"."name" IS '昵称';
COMMENT ON COLUMN "public"."ai_user"."password" IS '密码';
COMMENT ON COLUMN "public"."ai_user"."salt" IS '盐值';
COMMENT ON COLUMN "public"."ai_user"."status" IS '状态';
COMMENT ON COLUMN "public"."ai_user"."create_by" IS '创建人';
COMMENT ON COLUMN "public"."ai_user"."update_by" IS '修改人';
COMMENT ON COLUMN "public"."ai_user"."create_time" IS '创建时间';
COMMENT ON COLUMN "public"."ai_user"."update_time" IS '修改时间';
COMMENT ON COLUMN "public"."ai_user"."del_flag" IS '逻辑删除';

-- ----------------------------
-- Table structure for ai_user_role_rel
-- ----------------------------
DROP TABLE IF EXISTS "public"."ai_user_role_rel";
CREATE TABLE "public"."ai_user_role_rel"
(
    "id"          int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1
        MINVALUE 1
        MAXVALUE 9223372036854775807
        START 1
        CACHE 1
        ),
    "user_id"     int8 NOT NULL,
    "role_id"     int8 NOT NULL,
    "create_by"   varchar(255) COLLATE "pg_catalog"."default",
    "update_by"   varchar(255) COLLATE "pg_catalog"."default",
    "create_time" timestamp(6) DEFAULT now(),
    "update_time" timestamp(6) DEFAULT now(),
    "del_flag"    bool         DEFAULT false
)
;
ALTER TABLE "public"."ai_user_role_rel"
    OWNER TO "root";
COMMENT ON COLUMN "public"."ai_user_role_rel"."id" IS 'id';
COMMENT ON COLUMN "public"."ai_user_role_rel"."user_id" IS '用户ID';
COMMENT ON COLUMN "public"."ai_user_role_rel"."role_id" IS '角色ID';
COMMENT ON COLUMN "public"."ai_user_role_rel"."create_by" IS '创建人';
COMMENT ON COLUMN "public"."ai_user_role_rel"."update_by" IS '修改人';
COMMENT ON COLUMN "public"."ai_user_role_rel"."create_time" IS '创建时间';
COMMENT ON COLUMN "public"."ai_user_role_rel"."update_time" IS '修改时间';
COMMENT ON COLUMN "public"."ai_user_role_rel"."del_flag" IS '逻辑删除';

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."ai_chat_id_seq"
    OWNED BY "public"."ai_chat"."id";
SELECT setval('"public"."ai_chat_id_seq"', 1, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."ai_chat_record_id_seq"
    OWNED BY "public"."ai_chat_record"."id";
SELECT setval('"public"."ai_chat_record_id_seq"', 1, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."ai_chat_record_msg_id_seq"
    OWNED BY "public"."ai_chat_record_msg"."id";
SELECT setval('"public"."ai_chat_record_msg_id_seq"', 1, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."ai_role_id_seq"
    OWNED BY "public"."ai_role"."id";
SELECT setval('"public"."ai_role_id_seq"', 1, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."ai_user_id_seq"
    OWNED BY "public"."ai_user"."id";
SELECT setval('"public"."ai_user_id_seq"', 1, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."ai_user_role_rel_id_seq"
    OWNED BY "public"."ai_user_role_rel"."id";
SELECT setval('"public"."ai_user_role_rel_id_seq"', 1, false);

-- ----------------------------
-- Indexes structure for table ai_chat
-- ----------------------------
CREATE INDEX "idx_user_id" ON "public"."ai_chat" USING btree (
                                                              "user_id" "pg_catalog"."int8_ops" ASC NULLS LAST
    );

-- ----------------------------
-- Primary Key structure for table ai_chat
-- ----------------------------
ALTER TABLE "public"."ai_chat"
    ADD CONSTRAINT "ai_chat_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Indexes structure for table ai_chat_record
-- ----------------------------
CREATE INDEX "idx_chat_id" ON "public"."ai_chat_record" USING btree (
                                                                     "chat_id" "pg_catalog"."int8_ops" ASC NULLS LAST
    );
CREATE INDEX "idx_name" ON "public"."ai_chat_record" USING btree (
                                                                  "name" COLLATE "pg_catalog"."default"
                                                                  "pg_catalog"."text_ops" ASC NULLS LAST
    );
CREATE INDEX "idx_parent_id" ON "public"."ai_chat_record" USING btree (
                                                                       "parent_id" "pg_catalog"."int8_ops" ASC NULLS
                                                                       LAST
    );

-- ----------------------------
-- Primary Key structure for table ai_chat_record
-- ----------------------------
ALTER TABLE "public"."ai_chat_record"
    ADD CONSTRAINT "ai_chat_record_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table ai_chat_record_msg
-- ----------------------------
ALTER TABLE "public"."ai_chat_record_msg"
    ADD CONSTRAINT "ai_chat_record_msg_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table ai_role
-- ----------------------------
ALTER TABLE "public"."ai_role"
    ADD CONSTRAINT "ai_role_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Indexes structure for table ai_user
-- ----------------------------
CREATE UNIQUE INDEX "idx_account_no" ON "public"."ai_user" USING btree (
                                                                        "account_no" COLLATE "pg_catalog"."default"
                                                                        "pg_catalog"."text_ops" ASC NULLS LAST
    );

-- ----------------------------
-- Primary Key structure for table ai_user
-- ----------------------------
ALTER TABLE "public"."ai_user"
    ADD CONSTRAINT "ai_user_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table ai_user_role_rel
-- ----------------------------
ALTER TABLE "public"."ai_user_role_rel"
    ADD CONSTRAINT "ai_user_role_rel_pkey" PRIMARY KEY ("id");
